{% set name = "architector" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/architector-{{ version }}.tar.gz
  sha256: d9588a95e9781296d3b6af798eebb50e78924755afd384931ef8e813fc6f0c64

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - ase
    - numpy
    - numba
    - py3dmol
    - openbabel
    - scipy
    - pandas
    - xtb-python
    - pynauty
    - openbabel
    - mendeleev
    - tqdm

test:
  imports:
    - architector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanl/Architector
  summary: The architector python package - for 3D inorganometallic complex design.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgt16-lanl
    - jan-janssen
