{% set name = "architector" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/architector-{{ version }}.tar.gz
  sha256: fe63d597d6b5813822d05b866d4742db4f5d9215dacd95519e39acd4649dcd33

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - ase
    - numpy
    - numba
    - py3dmol
    - openbabel
    - scipy
    - pandas
    - xtb-python
    - pynauty
    - openbabel
    - mendeleev
    - tqdm

test:
  imports:
    - architector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lanl/Architector
  summary: The architector python package - for 3D inorganometallic complex design.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgt16-lanl
    - jan-janssen
